# Generated by Django 5.0.1 on 2024-01-31 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_members_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='middlename',
        ),
    ]
